version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PREFECT_API_URL: http://server:4200/api
    init: true
  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      PREFECT_API_URL: http://server:4200/api
    volumes:
      - ./src:/app/src
    init: true
